export enum Events {
  JOIN_ROOM = "JOIN_ROOM",
  JOIN_ROOM_UPDATE = "JOIN_ROOM_UPDATE",
  LEAVE_ROOM = "LEAVE_ROOM",
  LEAVE_ROOM_UPDATE = "LEAVE_ROOM_UPDATE",
  SEND_MESSAGE = "SEND_MESSAGE",
  SEND_MESSAGE_UPDATE = "SEND_MESSAGE_UPDATE",
  DISSCONNECT = "disconnect", //reserved name for socketIO
  ON_SEEK = "ON_SEEK",
  ON_SEEK_UPDATE = "ON_SEEK_UPDATE",
  ON_PLAYPAUSE = "ON_PLAYPAUSE",
  ON_PLAYPAUSE_UPDATE = "ON_PLAYPAUSE_UPDATE",
}